FROM golang:1.25-alpine AS build

WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o /out/api ./services/api

FROM alpine:3.22

WORKDIR /app
COPY --from=build /out/api /app/api
EXPOSE 8080 6060
ENTRYPOINT ["/app/api"]
